apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mirjmessage-deployment
spec:
  selector:
    matchLabels:
      app: mirjmessage
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: mirjmessage
    spec:
      containers:
        - name: mirjmessage
          image: quaqmre/kube:mirjmessage
          ports:
            - containerPort: 9001
