// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: mirjmessage.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Input int32

const (
	Input_LSROOM Input = 0
	Input_LSUSER Input = 1
	Input_MKROOM Input = 2
	Input_RMROOM Input = 3
	Input_JOIN   Input = 4
	Input_EXIT   Input = 5
	Input_CHNAME Input = 6
)

// Enum value maps for Input.
var (
	Input_name = map[int32]string{
		0: "LSROOM",
		1: "LSUSER",
		2: "MKROOM",
		3: "RMROOM",
		4: "JOIN",
		5: "EXIT",
		6: "CHNAME",
	}
	Input_value = map[string]int32{
		"LSROOM": 0,
		"LSUSER": 1,
		"MKROOM": 2,
		"RMROOM": 3,
		"JOIN":   4,
		"EXIT":   5,
		"CHNAME": 6,
	}
)

func (x Input) Enum() *Input {
	p := new(Input)
	*p = x
	return p
}

func (x Input) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Input) Descriptor() protoreflect.EnumDescriptor {
	return file_mirjmessage_proto_enumTypes[0].Descriptor()
}

func (Input) Type() protoreflect.EnumType {
	return &file_mirjmessage_proto_enumTypes[0]
}

func (x Input) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Input.Descriptor instead.
func (Input) EnumDescriptor() ([]byte, []int) {
	return file_mirjmessage_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Content:
	//	*Message_Letter
	Content isMessage_Content `protobuf_oneof:"content"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mirjmessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_mirjmessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_mirjmessage_proto_rawDescGZIP(), []int{0}
}

func (m *Message) GetContent() isMessage_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *Message) GetLetter() *Letter {
	if x, ok := x.GetContent().(*Message_Letter); ok {
		return x.Letter
	}
	return nil
}

type isMessage_Content interface {
	isMessage_Content()
}

type Message_Letter struct {
	Letter *Letter `protobuf:"bytes,1,opt,name=letter,proto3,oneof"`
}

func (*Message_Letter) isMessage_Content() {}

type UserMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Content:
	//	*UserMessage_Join
	//	*UserMessage_Left
	//	*UserMessage_Command
	//	*UserMessage_Letter
	Content isUserMessage_Content `protobuf_oneof:"content"`
}

func (x *UserMessage) Reset() {
	*x = UserMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mirjmessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMessage) ProtoMessage() {}

func (x *UserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mirjmessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMessage.ProtoReflect.Descriptor instead.
func (*UserMessage) Descriptor() ([]byte, []int) {
	return file_mirjmessage_proto_rawDescGZIP(), []int{1}
}

func (m *UserMessage) GetContent() isUserMessage_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *UserMessage) GetJoin() *Join {
	if x, ok := x.GetContent().(*UserMessage_Join); ok {
		return x.Join
	}
	return nil
}

func (x *UserMessage) GetLeft() *Left {
	if x, ok := x.GetContent().(*UserMessage_Left); ok {
		return x.Left
	}
	return nil
}

func (x *UserMessage) GetCommand() *Command {
	if x, ok := x.GetContent().(*UserMessage_Command); ok {
		return x.Command
	}
	return nil
}

func (x *UserMessage) GetLetter() *Letter {
	if x, ok := x.GetContent().(*UserMessage_Letter); ok {
		return x.Letter
	}
	return nil
}

type isUserMessage_Content interface {
	isUserMessage_Content()
}

type UserMessage_Join struct {
	Join *Join `protobuf:"bytes,1,opt,name=join,proto3,oneof"`
}

type UserMessage_Left struct {
	Left *Left `protobuf:"bytes,2,opt,name=left,proto3,oneof"`
}

type UserMessage_Command struct {
	Command *Command `protobuf:"bytes,3,opt,name=command,proto3,oneof"`
}

type UserMessage_Letter struct {
	Letter *Letter `protobuf:"bytes,4,opt,name=letter,proto3,oneof"`
}

func (*UserMessage_Join) isUserMessage_Content() {}

func (*UserMessage_Left) isUserMessage_Content() {}

func (*UserMessage_Command) isUserMessage_Content() {}

func (*UserMessage_Letter) isUserMessage_Content() {}

type Singin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *Singin) Reset() {
	*x = Singin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mirjmessage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Singin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Singin) ProtoMessage() {}

func (x *Singin) ProtoReflect() protoreflect.Message {
	mi := &file_mirjmessage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Singin.ProtoReflect.Descriptor instead.
func (*Singin) Descriptor() ([]byte, []int) {
	return file_mirjmessage_proto_rawDescGZIP(), []int{2}
}

func (x *Singin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Singin) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Join struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *Join) Reset() {
	*x = Join{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mirjmessage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Join) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Join) ProtoMessage() {}

func (x *Join) ProtoReflect() protoreflect.Message {
	mi := &file_mirjmessage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Join.ProtoReflect.Descriptor instead.
func (*Join) Descriptor() ([]byte, []int) {
	return file_mirjmessage_proto_rawDescGZIP(), []int{3}
}

func (x *Join) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Join) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Left struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Left) Reset() {
	*x = Left{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mirjmessage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Left) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Left) ProtoMessage() {}

func (x *Left) ProtoReflect() protoreflect.Message {
	mi := &file_mirjmessage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Left.ProtoReflect.Descriptor instead.
func (*Left) Descriptor() ([]byte, []int) {
	return file_mirjmessage_proto_rawDescGZIP(), []int{4}
}

type Letter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Letter) Reset() {
	*x = Letter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mirjmessage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Letter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Letter) ProtoMessage() {}

func (x *Letter) ProtoReflect() protoreflect.Message {
	mi := &file_mirjmessage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Letter.ProtoReflect.Descriptor instead.
func (*Letter) Descriptor() ([]byte, []int) {
	return file_mirjmessage_proto_rawDescGZIP(), []int{5}
}

func (x *Letter) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input   Input  `protobuf:"varint,1,opt,name=input,proto3,enum=mirjmessage.Input" json:"input,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mirjmessage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_mirjmessage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_mirjmessage_proto_rawDescGZIP(), []int{6}
}

func (x *Command) GetInput() Input {
	if x != nil {
		return x.Input
	}
	return Input_LSROOM
}

func (x *Command) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_mirjmessage_proto protoreflect.FileDescriptor

var file_mirjmessage_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6d, 0x69, 0x72, 0x6a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x69, 0x72, 0x6a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x43, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x6c,
	0x65, 0x74, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x69,
	0x72, 0x6a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72,
	0x48, 0x00, 0x52, 0x06, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0xcb, 0x01, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x6a, 0x6f, 0x69, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x69, 0x72, 0x6a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x48, 0x00, 0x52, 0x04, 0x6a, 0x6f, 0x69, 0x6e, 0x12, 0x27,
	0x0a, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d,
	0x69, 0x72, 0x6a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4c, 0x65, 0x66, 0x74, 0x48,
	0x00, 0x52, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x12, 0x30, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x69, 0x72, 0x6a, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00,
	0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x2d, 0x0a, 0x06, 0x6c, 0x65, 0x74,
	0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x69, 0x72, 0x6a,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x48, 0x00,
	0x52, 0x06, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x22, 0x38, 0x0a, 0x06, 0x53, 0x69, 0x6e, 0x67, 0x69, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x36, 0x0a,
	0x04, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x06, 0x0a, 0x04, 0x4c, 0x65, 0x66, 0x74, 0x22, 0x22, 0x0a,
	0x06, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x4d, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x28, 0x0a, 0x05,
	0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x6d, 0x69,
	0x72, 0x6a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52,
	0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2a, 0x57, 0x0a, 0x05, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x53, 0x52,
	0x4f, 0x4f, 0x4d, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x53, 0x55, 0x53, 0x45, 0x52, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x4b, 0x52, 0x4f, 0x4f, 0x4d, 0x10, 0x02, 0x12, 0x0a, 0x0a,
	0x06, 0x52, 0x4d, 0x52, 0x4f, 0x4f, 0x4d, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x4f, 0x49,
	0x4e, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x45, 0x58, 0x49, 0x54, 0x10, 0x05, 0x12, 0x0a, 0x0a,
	0x06, 0x43, 0x48, 0x4e, 0x41, 0x4d, 0x45, 0x10, 0x06, 0x42, 0x04, 0x5a, 0x02, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mirjmessage_proto_rawDescOnce sync.Once
	file_mirjmessage_proto_rawDescData = file_mirjmessage_proto_rawDesc
)

func file_mirjmessage_proto_rawDescGZIP() []byte {
	file_mirjmessage_proto_rawDescOnce.Do(func() {
		file_mirjmessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_mirjmessage_proto_rawDescData)
	})
	return file_mirjmessage_proto_rawDescData
}

var file_mirjmessage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mirjmessage_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_mirjmessage_proto_goTypes = []interface{}{
	(Input)(0),          // 0: mirjmessage.Input
	(*Message)(nil),     // 1: mirjmessage.Message
	(*UserMessage)(nil), // 2: mirjmessage.UserMessage
	(*Singin)(nil),      // 3: mirjmessage.Singin
	(*Join)(nil),        // 4: mirjmessage.Join
	(*Left)(nil),        // 5: mirjmessage.Left
	(*Letter)(nil),      // 6: mirjmessage.Letter
	(*Command)(nil),     // 7: mirjmessage.Command
}
var file_mirjmessage_proto_depIdxs = []int32{
	6, // 0: mirjmessage.Message.letter:type_name -> mirjmessage.Letter
	4, // 1: mirjmessage.UserMessage.join:type_name -> mirjmessage.Join
	5, // 2: mirjmessage.UserMessage.left:type_name -> mirjmessage.Left
	7, // 3: mirjmessage.UserMessage.command:type_name -> mirjmessage.Command
	6, // 4: mirjmessage.UserMessage.letter:type_name -> mirjmessage.Letter
	0, // 5: mirjmessage.Command.input:type_name -> mirjmessage.Input
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_mirjmessage_proto_init() }
func file_mirjmessage_proto_init() {
	if File_mirjmessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mirjmessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mirjmessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mirjmessage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Singin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mirjmessage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Join); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mirjmessage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Left); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mirjmessage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Letter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mirjmessage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_mirjmessage_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Message_Letter)(nil),
	}
	file_mirjmessage_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*UserMessage_Join)(nil),
		(*UserMessage_Left)(nil),
		(*UserMessage_Command)(nil),
		(*UserMessage_Letter)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mirjmessage_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mirjmessage_proto_goTypes,
		DependencyIndexes: file_mirjmessage_proto_depIdxs,
		EnumInfos:         file_mirjmessage_proto_enumTypes,
		MessageInfos:      file_mirjmessage_proto_msgTypes,
	}.Build()
	File_mirjmessage_proto = out.File
	file_mirjmessage_proto_rawDesc = nil
	file_mirjmessage_proto_goTypes = nil
	file_mirjmessage_proto_depIdxs = nil
}
