// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: mirjmessage.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ClientInput int32

const (
	ClientInput_LSROOM ClientInput = 0
	ClientInput_LSUSER ClientInput = 1
)

// Enum value maps for ClientInput.
var (
	ClientInput_name = map[int32]string{
		0: "LSROOM",
		1: "LSUSER",
	}
	ClientInput_value = map[string]int32{
		"LSROOM": 0,
		"LSUSER": 1,
	}
)

func (x ClientInput) Enum() *ClientInput {
	p := new(ClientInput)
	*p = x
	return p
}

func (x ClientInput) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientInput) Descriptor() protoreflect.EnumDescriptor {
	return file_mirjmessage_proto_enumTypes[0].Descriptor()
}

func (ClientInput) Type() protoreflect.EnumType {
	return &file_mirjmessage_proto_enumTypes[0]
}

func (x ClientInput) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientInput.Descriptor instead.
func (ClientInput) EnumDescriptor() ([]byte, []int) {
	return file_mirjmessage_proto_rawDescGZIP(), []int{0}
}

type UserMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Content:
	//	*UserMessage_ClientJoin
	//	*UserMessage_ClientLeft
	//	*UserMessage_ClientCommand
	//	*UserMessage_ClientMessage
	Content isUserMessage_Content `protobuf_oneof:"content"`
}

func (x *UserMessage) Reset() {
	*x = UserMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mirjmessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMessage) ProtoMessage() {}

func (x *UserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mirjmessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMessage.ProtoReflect.Descriptor instead.
func (*UserMessage) Descriptor() ([]byte, []int) {
	return file_mirjmessage_proto_rawDescGZIP(), []int{0}
}

func (m *UserMessage) GetContent() isUserMessage_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *UserMessage) GetClientJoin() *ClientJoin {
	if x, ok := x.GetContent().(*UserMessage_ClientJoin); ok {
		return x.ClientJoin
	}
	return nil
}

func (x *UserMessage) GetClientLeft() *ClientLeft {
	if x, ok := x.GetContent().(*UserMessage_ClientLeft); ok {
		return x.ClientLeft
	}
	return nil
}

func (x *UserMessage) GetClientCommand() *ClientCommand {
	if x, ok := x.GetContent().(*UserMessage_ClientCommand); ok {
		return x.ClientCommand
	}
	return nil
}

func (x *UserMessage) GetClientMessage() *ClientMessage {
	if x, ok := x.GetContent().(*UserMessage_ClientMessage); ok {
		return x.ClientMessage
	}
	return nil
}

type isUserMessage_Content interface {
	isUserMessage_Content()
}

type UserMessage_ClientJoin struct {
	ClientJoin *ClientJoin `protobuf:"bytes,1,opt,name=clientJoin,proto3,oneof"`
}

type UserMessage_ClientLeft struct {
	ClientLeft *ClientLeft `protobuf:"bytes,2,opt,name=clientLeft,proto3,oneof"`
}

type UserMessage_ClientCommand struct {
	ClientCommand *ClientCommand `protobuf:"bytes,3,opt,name=clientCommand,proto3,oneof"`
}

type UserMessage_ClientMessage struct {
	ClientMessage *ClientMessage `protobuf:"bytes,4,opt,name=clientMessage,proto3,oneof"`
}

func (*UserMessage_ClientJoin) isUserMessage_Content() {}

func (*UserMessage_ClientLeft) isUserMessage_Content() {}

func (*UserMessage_ClientCommand) isUserMessage_Content() {}

func (*UserMessage_ClientMessage) isUserMessage_Content() {}

type Singin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *Singin) Reset() {
	*x = Singin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mirjmessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Singin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Singin) ProtoMessage() {}

func (x *Singin) ProtoReflect() protoreflect.Message {
	mi := &file_mirjmessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Singin.ProtoReflect.Descriptor instead.
func (*Singin) Descriptor() ([]byte, []int) {
	return file_mirjmessage_proto_rawDescGZIP(), []int{1}
}

func (x *Singin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Singin) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ClientJoin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *ClientJoin) Reset() {
	*x = ClientJoin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mirjmessage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientJoin) ProtoMessage() {}

func (x *ClientJoin) ProtoReflect() protoreflect.Message {
	mi := &file_mirjmessage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientJoin.ProtoReflect.Descriptor instead.
func (*ClientJoin) Descriptor() ([]byte, []int) {
	return file_mirjmessage_proto_rawDescGZIP(), []int{2}
}

func (x *ClientJoin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClientJoin) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ClientLeft struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClientLeft) Reset() {
	*x = ClientLeft{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mirjmessage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientLeft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientLeft) ProtoMessage() {}

func (x *ClientLeft) ProtoReflect() protoreflect.Message {
	mi := &file_mirjmessage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientLeft.ProtoReflect.Descriptor instead.
func (*ClientLeft) Descriptor() ([]byte, []int) {
	return file_mirjmessage_proto_rawDescGZIP(), []int{3}
}

type ClientMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mirjmessage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mirjmessage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_mirjmessage_proto_rawDescGZIP(), []int{4}
}

func (x *ClientMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ClientCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientInput ClientInput `protobuf:"varint,1,opt,name=clientInput,proto3,enum=mirjmessage.ClientInput" json:"clientInput,omitempty"`
}

func (x *ClientCommand) Reset() {
	*x = ClientCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mirjmessage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientCommand) ProtoMessage() {}

func (x *ClientCommand) ProtoReflect() protoreflect.Message {
	mi := &file_mirjmessage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientCommand.ProtoReflect.Descriptor instead.
func (*ClientCommand) Descriptor() ([]byte, []int) {
	return file_mirjmessage_proto_rawDescGZIP(), []int{5}
}

func (x *ClientCommand) GetClientInput() ClientInput {
	if x != nil {
		return x.ClientInput
	}
	return ClientInput_LSROOM
}

var File_mirjmessage_proto protoreflect.FileDescriptor

var file_mirjmessage_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6d, 0x69, 0x72, 0x6a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x69, 0x72, 0x6a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x96, 0x02, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x39, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x69, 0x72, 0x6a, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x48, 0x00, 0x52,
	0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x39, 0x0a, 0x0a, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4c, 0x65, 0x66, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x6d, 0x69, 0x72, 0x6a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x4c, 0x65, 0x66, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x4c, 0x65, 0x66, 0x74, 0x12, 0x42, 0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x6d, 0x69, 0x72, 0x6a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x0d, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x42, 0x0a, 0x0d, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x69, 0x72, 0x6a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52,
	0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x09,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x38, 0x0a, 0x06, 0x53, 0x69, 0x6e,
	0x67, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x22, 0x3c, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4a, 0x6f, 0x69,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x22, 0x0c, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4c, 0x65, 0x66, 0x74, 0x22,
	0x29, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x4b, 0x0a, 0x0d, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x3a, 0x0a, 0x0b, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x18, 0x2e, 0x6d, 0x69, 0x72, 0x6a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x0b, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x2a, 0x25, 0x0a, 0x0b, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x53, 0x52, 0x4f, 0x4f, 0x4d,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x53, 0x55, 0x53, 0x45, 0x52, 0x10, 0x01, 0x42, 0x04,
	0x5a, 0x02, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mirjmessage_proto_rawDescOnce sync.Once
	file_mirjmessage_proto_rawDescData = file_mirjmessage_proto_rawDesc
)

func file_mirjmessage_proto_rawDescGZIP() []byte {
	file_mirjmessage_proto_rawDescOnce.Do(func() {
		file_mirjmessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_mirjmessage_proto_rawDescData)
	})
	return file_mirjmessage_proto_rawDescData
}

var file_mirjmessage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mirjmessage_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_mirjmessage_proto_goTypes = []interface{}{
	(ClientInput)(0),      // 0: mirjmessage.ClientInput
	(*UserMessage)(nil),   // 1: mirjmessage.UserMessage
	(*Singin)(nil),        // 2: mirjmessage.Singin
	(*ClientJoin)(nil),    // 3: mirjmessage.ClientJoin
	(*ClientLeft)(nil),    // 4: mirjmessage.ClientLeft
	(*ClientMessage)(nil), // 5: mirjmessage.ClientMessage
	(*ClientCommand)(nil), // 6: mirjmessage.ClientCommand
}
var file_mirjmessage_proto_depIdxs = []int32{
	3, // 0: mirjmessage.UserMessage.clientJoin:type_name -> mirjmessage.ClientJoin
	4, // 1: mirjmessage.UserMessage.clientLeft:type_name -> mirjmessage.ClientLeft
	6, // 2: mirjmessage.UserMessage.clientCommand:type_name -> mirjmessage.ClientCommand
	5, // 3: mirjmessage.UserMessage.clientMessage:type_name -> mirjmessage.ClientMessage
	0, // 4: mirjmessage.ClientCommand.clientInput:type_name -> mirjmessage.ClientInput
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_mirjmessage_proto_init() }
func file_mirjmessage_proto_init() {
	if File_mirjmessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mirjmessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mirjmessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Singin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mirjmessage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientJoin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mirjmessage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientLeft); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mirjmessage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mirjmessage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_mirjmessage_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*UserMessage_ClientJoin)(nil),
		(*UserMessage_ClientLeft)(nil),
		(*UserMessage_ClientCommand)(nil),
		(*UserMessage_ClientMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mirjmessage_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mirjmessage_proto_goTypes,
		DependencyIndexes: file_mirjmessage_proto_depIdxs,
		EnumInfos:         file_mirjmessage_proto_enumTypes,
		MessageInfos:      file_mirjmessage_proto_msgTypes,
	}.Build()
	File_mirjmessage_proto = out.File
	file_mirjmessage_proto_rawDesc = nil
	file_mirjmessage_proto_goTypes = nil
	file_mirjmessage_proto_depIdxs = nil
}
